#!/bin/bash

ln -s ~/.dotfiles/bash/aliases ~/.aliases
ln -s ~/.dotfiles/bash/bash_profile ~/.bash_profile
ln -s ~/.dotfiles/bash/bashrc ~/.bashrc
ln -s ~/.dotfiles/bash/ubuntu_bashrc ~/.ubuntu_bashrc

ln -s ~/.dotfiles/git/gitconfig ~/.gitconfig

ln -s ~/.dotfiles/hg/hgrc ~/.hgrc

ln -s ~/.dotfiles/screen/screenrc ~/.screenrc

ln -s ~/.dotfiles/vim/vimrc ~/.vimrc
ln -s ~/.dotfiles/vim ~/.vim

ln -s ~/.dotfiles/bin/ix ~/bin/ix
