set nocompatible
set mouse=nv
let mapleader = ","

:imap ;; <Esc>
:imap ii <Esc>

set noswapfile

"encoding and file formats
set encoding=utf8
try
    lang en_US
catch
endtry

set background=dark
colorscheme delek

syntax on

set title
let &titleold=hostname()
set titlestring=%t%(\ %M%)%(\ (%{expand(\"%:p:h\")})%)%(\ %a%)\ -\ %{hostname()}

set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set laststatus=2

" Source the vimrc file after saving it
if has("autocmd")
   autocmd bufwritepost .vimrc source $MYVIMRC
endif

if has("autocmd")
    filetype indent plugin on
endif

set expandtab
set smarttab

set tabstop=4
set shiftwidth=4
set softtabstop=4

set modeline

set scrolloff=5 " keep at least 5 lines above/below

" Highlight line under cursor
" set cursorline
" hi CursorLine term=none cterm=none

" Create Blank Newlines and stay in Normal mode
nnoremap <silent> zj o<Esc>
nnoremap <silent> zk O<Esc>

" Fix Ctrl-U and Ctrl-W
" http://vim.wikia.com/wiki/Recover_from_accidental_Ctrl-U
inoremap <c-u> <c-g>u<c-u>
inoremap <c-w> <c-g>u<c-w>

" easier moving of code blocks
vnoremap < <gv " better indentation
vnoremap > >gv " better indentation

" Line Numbers, Yay!
set number

" Buffers
map <C-j> :bprev<CR>
map <C-k> :bnext<CR>
set hidden " this will go along

nmap <leader>l :set list!<CR>
set list
set listchars=tab:>.,eol:¬
nmap <leader>v :tabedit $MYVIMRC<CR>

" Function keys
map <F1> <Esc>:w<CR>
map! <F1> <Esc>:w<CR>
nmap <F2> <Esc>:set nonumber!<CR>:set invpaste<CR>:set list!<CR>
imap <F2> <Esc>:set nonumber!<CR>:set invpaste<CR>:set list!<CR>
map <Leader><F2> :set foldenable!<CR>
map <Leader><F3> :call <SID>StripTrailingWhitespaces()<CR>
" F8 == <C-[>OW
