set nocompatible

" git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

" My bundles
Bundle 'Shougo/neocomplcache.vim'
Bundle 'Raimondi/delimitMate'
Bundle 'Yggdroot/indentLine'
Bundle 'tpope/vim-fugitive'
Bundle 'kien/ctrlp.vim'
Bundle 'reinh/vim-makegreen'
Bundle 'airblade/vim-gitgutter'
Bundle 'hynek/vim-python-pep8-indent'
Bundle 'tell-k/vim-autopep8'
"let g:autopep8_disable_show_diff=1
noremap <buffer> <F8> :call Autopep8()<CR><C-L>

set mouse=nv
let mapleader = ","

set noswapfile

"make searches case insensitive
set ignorecase
"except when I type a capital letter in the search
set smartcase

"encoding and file formats
set encoding=utf8
try
    lang en_US
catch
endtry

set background=dark
try
    colorscheme vividchalk
catch /^Vim\%((\a\+)\)\=:E185/
    :silent
endtry

syntax on

set title
let &titleold=hostname()
set titlestring=%t%(\ %M%)%(\ (%{expand(\"%:p:h\")})%)%(\ %a%)\ -\ %{hostname()}

set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set laststatus=2

" Source the vimrc file after saving it
if has("autocmd")
    autocmd bufwritepost .vimrc source $MYVIMRC
endif

if has("autocmd")
    filetype indent plugin on
endif

set expandtab
set smarttab

set tabstop=4
set shiftwidth=4
set softtabstop=4

set modeline

set scrolloff=5 " keep at least 5 lines above/below

" Highlight line under cursor
" set cursorline
" hi CursorLine term=none cterm=none

" Create Blank Newlines and stay in Normal mode
nnoremap <silent> zj o<Esc>
nnoremap <silent> zk O<Esc>

" delete the current line and then insert a new one, with proper indent
nnoremap I ddko

" Begining & End of line in Normal mode
noremap H ^
noremap L g_

" Fix Ctrl-U and Ctrl-W
" http://vim.wikia.com/wiki/Recover_from_accidental_Ctrl-U
inoremap <c-u> <c-g>u<c-u>
inoremap <c-w> <c-g>u<c-w>

" move blocks of text up/down
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <Esc>:m .+1<CR>==gi
inoremap <C-k> <Esc>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

" easier moving of code blocks
vnoremap < <gv " better indentation
vnoremap > >gv " better indentation
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
vnoremap <S-Tab> <
vnoremap <Tab> >

" Use the system copy buffer!
vnoremap <C-c> "+y
vnoremap <C-x> "+x
noremap <C-v> "+P
noremap! <C-v> <Esc>"+P

" Line Numbers, Yay!
set number

nnoremap <leader>l :set list!<CR>
set list
set listchars=tab:»·,trail:·
    
	
set showbreak=↪

highlight SpecialKey ctermfg=Red guifg=Red
"highlight NonText cterm=reverse

nnoremap <leader>v :tabedit $MYVIMRC<CR>
noremap h :tabprevious<CR>
noremap l :tabnext<CR>
noremap <C-o> <Esc>:tabnew<CR>:e .<CR>

" Function keys
noremap <F1> <Esc>:w<CR>
noremap! <F1> <Esc>:w<CR>
nnoremap <F2> <Esc>:set nonumber!<CR>:set invpaste<CR>:set list!<CR>
inoremap <F2> <Esc>:set nonumber!<CR>:set invpaste<CR>:set list!<CR>
noremap <Leader><F2> :set foldenable!<CR>
noremap <F3> <Esc>gg=G''
noremap! <F3> <Esc>gg=G''
" map <Leader><F3> :call <SID>StripTrailingWhitespaces()<CR>
" F8 == <C-[>OW

" Execute file being edited with F5:
noremap <buffer> <F5> <Esc>:w<CR>:!./% <CR>
noremap <buffer> <C-[>OT <Esc>:w<CR>:!./% <CR>


let g:neocomplcache_enable_at_startup = 1
