# From: https://github.com/mathiasbynens/dotfiles/blob/master/.bashrc
[ -n "$PS1" ] && source ~/.bash_profile

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

if [ -n "$DISPLAY" -a "$TERM" == "xterm" ]; then
    export TERM=xterm-256color
fi

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
