# From: https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile

# some environment defaults
EMAIL="Andrew Thompson <andrewkt@aktzero.com>"
EDITOR="vi"

DEBFULLNAME="Andrew Thompson"
DEBEMAIL="<andrewkt@aktzero.com>"

# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

source ~/.aliases

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=10000

# capture my SSH_AUTH for use in screen/tmux
if [[ "$STY" || "$TMUX" ]]; then
    if [[ -f ~/.sshauth-$HOSTNAME && -s ~/.sshauth-$HOSTNAME ]]; then
        export `cat ~/.sshauth-$HOSTNAME`
    fi
else
    env | grep '^SSH_AUTH_SOCK' >~/.sshauth-$HOSTNAME
fi

# If possible, add tab completion for many more commands
#[ -f /etc/bash_completion ] && source /etc/bash_completion
if [ -f /etc/bash_completion ]; then
    if [ -f /etc/lsb-release ]; then
        DISTRIB_CODENAME=`grep "DISTRIB_CODENAME" /etc/lsb-release | cut -d = -f 2`
        case "$DISTRIB_CODENAME" in
            lucid);;
            precise);;
            *) source /etc/bash_completion ;;
        esac
        unset DISTRIB_CODENAME
    fi
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
