test -h ~/.bash_profile || echo "~/.bash_profile is not a symlink"
test -h ~/.bashrc || echo "~/.bashrc is not a symlink"

[ -n "$PS1" ] && source ~/.bash_profile

if [ -n "$DISPLAY" -a "$TERM" == "xterm" ]; then
    export TERM=xterm-256color
fi

test -x /usr/bin/setxkbmap && /usr/bin/setxkbmap -option "ctrl:nocaps"
bind -r '\C-s'
stty -ixon
stty stop undef

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
