# From: https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile

# some environment defaults
EMAIL="Andrew Thompson <andrewkt@aktzero.com>"
EDITOR="vi"

DEBFULLNAME="Andrew Thompson"
DEBEMAIL="<andrewkt@aktzero.com>"

# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$HOME/.local/bin:$HOME/.local/gems/bin:$PATH"

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don.t want to commit.
for file in ~/.{path,ubuntu_bashrc,bash_prompt,exports,aliases,functions,extra}; do
	[ -r "$file" ] && source "$file"
done
unset file

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=10000

# capture my SSH_AUTH for use in screen
# set | grep SSH_AUTH > ~/.sshauth # old method, need to test before i delete it
case "$TERM" in
    xterm) env | grep '^SSH_AUTH_SOCK' >~/.sshauth-$HOSTNAME;;
    xterm-256color) env | grep '^SSH_AUTH_SOCK' >~/.sshauth-$HOSTNAME;;
    screen) export `cat ~/.sshauth-$HOSTNAME`;;
    screen-256color) export `cat ~/.sshauth-$HOSTNAME`;;
esac

# Ruby gem local install folder
export GEM_HOME=~/.local/gems

# If possible, add tab completion for many more commands
#[ -f /etc/bash_completion ] && source /etc/bash_completion
if [ -f /etc/bash_completion ]; then
    if [ -f /etc/lsb-release ]; then
        DISTRIB_CODENAME=`grep "DISTRIB_CODENAME" /etc/lsb-release | cut -d = -f 2`
        case "$DISTRIB_CODENAME" in
            lucid);;
            precise);;
            *) source /etc/bash_completion ;;
        esac
        unset DISTRIB_CODENAME
    fi
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
