# From: https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile

# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don.t want to commit.
for file in ~/.{path,ubuntu_bashrc,bash_prompt,exports,aliases,functions,extra}; do
	[ -r "$file" ] && source "$file"
done
unset file

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=10000

# capture my SSH_AUTH for use in screen
# set | grep SSH_AUTH > ~/.sshauth # old method, need to test before i delete it
case "$TERM" in
    xterm) env | grep '^SSH_AUTH_SOCK' >~/.sshauth;;
    xterm-256color) env | grep '^SSH_AUTH_SOCK' >~/.sshauth;;
    screen) source ~/.sshauth;;
    screen-256color) source ~/.sshauth;;
esac

# If possible, add tab completion for many more commands
[ -f /etc/bash_completion ] && source /etc/bash_completion
